### ISSUE TITLE
Unable to create clone on Windows — illegal file name

### ISSUE THREAD

**Issue by hollasch** [JayBazuzi/Mobbing-Pattern-Language#7]
The file `Laptops? No!.md` is problematic on Windows. Here's output from my command line when attempting to clone:

```
$ git clone https://github.com/jaybazuzi/Mobbing-Pattern-Language.git
Cloning into 'Mobbing-Pattern-Language'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (14/14), done.

Receiving objects: 100% (198/198), 47.05 KiB | 2.35 MiB/s, done.
Resolving deltas: 100% (92/92), done.
error: unable to create file Laptops? No!.md: Invalid argument
error: unable to create file Patterns/Laptops? Yes!.md: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by JayBazuzi** [comment]
Sounds like a Windows bug to me.

**Comment by JayBazuzi** [comment]
But if you can think of a better name, go ahead and send a PR.

**Comment by hollasch** [comment]
Hard to do if I can't create a working clone. :D Lemme fire up my Mac...

**Comment by JayBazuzi** [comment]
You can edit on the GitHub site.

**Comment by hollasch** [comment]
_smacks forehead_

PR in flight.

**Comment by JayBazuzi** [comment]
Some things to think about when picking a new name:

- Would be nice if the Yes! and No! patterns alpha sort together. 
- Catchy names are good. But so are clear and obvious names.

I'm not sure if Windows-compatible file names really matter?

**Comment by hollasch** [comment]
Your call. Could function fine as a web-only repository for some users.
